using ElementalReactionsMod.Elements;
using ElementalReactionsMod.Loadout;
using System;
using System.Collections.Generic;
using System.Text;
using Unity.Collections;
using Unity.Jobs;
using UnityEngine;
using UnityEngine.Networking;
using RoR2;
using ElementalReactionsMod.Reactions;
using System.Linq;
using R2API;
using UnityEngine.Jobs;

namespace ElementalReactionsMod
{
    public class ElementalRain : MonoBehaviour
    {
        public static GameObject elementalRainPrefab;
        public static void Initialize()
        {
            elementalRainPrefab = PrefabAPI.CreateEmptyPrefab("ElementalRainManager");
            elementalRainPrefab.AddComponent<ElementalRain>();
            Stage.onServerStageBegin += TrySpawnElementalRain;
        }
        private static void TrySpawnElementalRain(Stage stage)
        {
            if (stage.sceneDef.cachedName == "moon2" || stage.sceneDef.cachedName == "meridian")
            {
                GameObject.Instantiate(elementalRainPrefab);
            }
        }
        
        public static ElementalRain instance;
        public ElementDef element;
        public void OnEnable()
        {
            SingletonHelper.Assign(ref instance, this);
            if (!element || element == DefaultElementDefs.physicalElement)
            {
                element = DefaultElementDefs.hydroElement;
            }
        }
        public void OnDisable()
        {
            SingletonHelper.Unassign(ref instance, this);
            CancelRaycastJob();
        }

        private float rainStopwatch;
        private const float rainInterval = 0.25f;
        private JobHandle? rainRaycastJob;
        private NativeArray<RaycastCommand> rainRaycastCommands;
        private NativeArray<RaycastHit> rainRaycastHitBuffer;
        private CharacterBody[] characterBodies;
        private void FixedUpdate()
        {
            if (NetworkServer.active)
            {
                if (this.rainRaycastJob != null)
                {
                    this.rainRaycastJob.Value.Complete();
                    this.rainRaycastJob = null;
                    RainApplyHydro();
                }
                this.rainStopwatch += Time.fixedDeltaTime;
                if (this.rainStopwatch >= rainInterval && element && element != DefaultElementDefs.physicalElement)
                {
                    this.rainStopwatch = Mathf.Min(this.rainStopwatch - rainInterval, 0f);
                    this.ScheduleRaycastJob();
                }
            }
        }
        private void RainApplyHydro()
        {
            for (int i = 0; i < characterBodies.Length; i++)
            {
                if (characterBodies[i] && rainRaycastHitBuffer[i].colliderInstanceID == 0 && !characterBodies[i].HasBuff(DLC1Content.Buffs.ImmuneToDebuffReady) &&
                    (!characterBodies[i].TryGetComponent<ElementLoadoutComponent>(out var loadout) || !loadout.permanentlyAppliedElement || loadout.permanentlyAppliedElement == DefaultElementDefs.physicalElement))
                {
                    ElementalReactionManager.ApplyElement(element, characterBodies[i], 0.25f);
                }
            }
            rainRaycastCommands.Dispose();
            rainRaycastHitBuffer.Dispose();
        }
        private void ScheduleRaycastJob()
        {
            CancelRaycastJob();
            // Copy CharacterBody list. Can't use original list directly because we can't have the list change between now and when we check again next frame
            characterBodies = CharacterBody.readOnlyInstancesList.ToArray();
            TransformAccessArray transformAccessArray = new TransformAccessArray(characterBodies.Length);
            // Copy all CharacterBody transforms to TransformAccessArray
            for (int i = 0; i < characterBodies.Length; i++)
            {
                transformAccessArray.Add(characterBodies[i].transform);
            }
            // A job creates the raycast commands using the TransformAccessArray
            this.rainRaycastCommands = new NativeArray<RaycastCommand>(characterBodies.Length, Allocator.TempJob);
            CreateRaycastCommandsJob createRaycastCommandsJob = new CreateRaycastCommandsJob
            {
                output = rainRaycastCommands,
                physicsScene = Physics.defaultPhysicsScene,
                raycastMask = LayerIndex.world.mask
            };
            // The job that actually does the raycasts, using the commands generated by the last job
            JobHandle createRaycastJobHandle = IJobParallelForTransformExtensions.ScheduleReadOnly(createRaycastCommandsJob, transformAccessArray, 32);
            this.rainRaycastHitBuffer = new NativeArray<RaycastHit>(characterBodies.Length, Allocator.TempJob);
            rainRaycastJob = RaycastCommand.ScheduleBatch(this.rainRaycastCommands, this.rainRaycastHitBuffer, characterBodies.Length, createRaycastJobHandle);
            transformAccessArray.Dispose();
        }
        private void CancelRaycastJob()
        {
            if (this.rainRaycastJob != null)
            {
                this.rainRaycastJob.GetValueOrDefault().Complete();
                rainRaycastCommands.Dispose();
                rainRaycastHitBuffer.Dispose();
            }
            this.rainRaycastJob = null;
        }
    }
    public struct CreateRaycastCommandsJob : IJobParallelForTransform
    {
        [ReadOnly]
        public PhysicsScene physicsScene;
        [ReadOnly]
        public LayerMask raycastMask;
        [WriteOnly]
        public NativeArray<RaycastCommand> output;
        public void Execute(int index, TransformAccess access)
        {
            output[index] = new RaycastCommand(physicsScene, access.position, Vector3.up, float.MaxValue, raycastMask, 1);
        }
    }
}
